---
- name: Hello Role example
  hosts: localhost
  vars:
    url_play: play.variable.example
  tasks:
    - name:
      debug:
        msg: varibletype = {{ url_play }}
      debug:
        msg: varibletype = {{ url_task }}
      vars:
        url_task: task.varible.example