---
- name: Hello Role example
  hosts: localhost
  vars:
    url_play: play.variable.example
  tasks:
    - name: play level varible
      debug:
        msg: varibletype = {{ url_play }}

    - name: task level varible example
      debug:
        msg: varibletype = {{ url_task }}
      vars:
        url_task: task.varible.example

    - name: run shell commands
      shell: uptime
      register: output

    - name: display command line output
      debug:
        msg: CML output = {{ output }}


