---
- name: template demo
  hosts: localhost
  tasks:
    - name: template example to copy the conf files
      copy:
        src: example.conf
        dest: /tmp/example-copy.conf

    - name: template example
      template:
        src: example.conf
        dest: /tmp/example-temp.conf